title: "[General] "
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
        value : |
          🌟 **Daily Scrum Report** 🌟
  - type : textarea
    id: Done
    attributes : 
      value : |
       ### ✅ 1. 어제 한 일 (What I did yesterday) 
       - 🔹 
  - type : markdown
    attributes : 
      value : |
        ### 📝 2. 오늘 할 일 (What I plan to do today) 
        🔹 각 사람별 오늘의 할일을 체크박스로 만든후 완료되면 췍
  - type: checkboxes
    attributes:
      label: 예진
      options:
        - label: 1번째
        - label: 2번째
  - type: checkboxes
    attributes:
      label: 용욱
      options:
        - label: 1번째
        - label: 2번째
  - type: checkboxes
    attributes:
      label: 정현
      options:
        - label: 1번째
        - label: 2번째
  - type: checkboxes
    attributes:
      label: 승찬
      options:
        - label: 1번째
        - label: 2번째
  - type : textarea
    id: Help
    attributes : 
      value : |
       ### ❓ 3. 문제점 및 도움 요청 (Any blockers or help needed?) 
        - 🔹
  - type : textarea
    id: Link
    attributes : 
      value : |
       ### 🔗 ** 알게된 사실 및 유용한 참고 관련 링크 (Links)**  
        - 🔹  
