title: "[General] "
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
        value : |
          🌟 **Daily Scrum Report** 🌟
  - type : textarea
    id: Done
    attributes :
      label: ✅ 1. 어제 한 일 (What I did yesterday) 
      value : |
       - 🔹 
