spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recoderdb
    username: recoder
    password: recoder
  mail:
    host: smtp.gmail.com
    port: 587
    username: jin200126
    password: xjyvaptpypcfhbvg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

mybatis:
  mapper-locations: mappers/**/*.xml

server:
  servlet:
    session:
      timeout=1800:

